linters-settings:
  errcheck:
    check-blank: true
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  goimports:
    local-prefixes: github.com/arr-ai/frozen
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gocritic:
    enabled-tags:
    - diagnostic
    - experimental
    - opinionated
    - performance
    - style

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
  - bodyclose
  - deadcode
  - depguard
  - dogsled
  - dupl
  - exportloopref
  - errcheck
  - funlen
  # - gochecknoglobals
  - gochecknoinits
  - gocognit
  # - godox
  - goconst
  # - gocritic
  - gocyclo
  - gofmt
  - goimports
  - gosec
  - gosimple
  - govet
  - ineffassign
  - lll
  - misspell
  - nakedret
  - revive
  - prealloc
  - staticcheck
  - structcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck
  - whitespace
  # - wsl
