linters-settings:
  errcheck:
    check-blank: true
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  goimports:
    local-prefixes: github.com/arr-ai/frozen
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
    - diagnostic
    - experimental
    - opinionated
    - performance
    - style

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
  - asciicheck
  # - bodyclose  # Broken for Go 1.18
  - cyclop
  - deadcode
  - depguard
  - dogsled
  - dupl
  - durationcheck
  - errcheck
  - errorlint
  - exhaustive
  # - exhaustivestruct
  - exportloopref
  - forbidigo
  # - forcetypeassert
  - funlen
  # - gci  # Broken for Go 1.18
  # - gochecknoglobals
  - gochecknoinits
  - gocognit
  - goconst
  # - gocritic
  - gocyclo
  - godot
  # - godox
  - goerr113
  - gofmt
  - gofumpt
  - goheader
  - goimports
  # - golint
  # - gomnd
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosec
  # - gosimple  # Broken for Go 1.18
  - govet
  # - ifshort
  - importas
  - ineffassign
  # - interfacer
  - lll
  - makezero
  # - maligned
  - misspell
  - nakedret
  - nestif
  # - nilerr  # Broken for Go 1.18
  # - nlreturn
  # - noctx  # Broken for Go 1.18
  - nolintlint
  - paralleltest
  - prealloc
  - predeclared
  # - promlinter
  # - revive  # Broken for Go 1.18
  # - rowserrcheck  # Broken for Go 1.18
  # - scopelint
  # - sqlclosecheck  # Broken for Go 1.18
  # - staticcheck  # Broken for Go 1.18
  # - structcheck  # Broken for Go 1.18
  # - stylecheck  # Broken for Go 1.18
  - tagliatelle
  # - testpackage
  - thelper
  # - tparallel  # Broken for Go 1.18
  # - typecheck
  - unconvert
  # - unparam  # Broken for Go 1.18
  # - unused  # Broken for Go 1.18
  - varcheck
  # - wastedassign  # Broken for Go 1.18
  - whitespace
  - wrapcheck
  # - wsl
