#!/usr/bin/perl

$PACKAGE = $ARGV[0];
$TYPE = $ARGV[1];

print "// Generated by gen-kv.pl $PACKAGE $TYPE. DO NOT EDIT.\n";

while (<STDIN>) {
    s{^package \w+$}{package $PACKAGE};
    if ($PACKAGE eq 'kvt') {
        s{(^package \w*)}{\1\nimport "github.com/arr-ai/frozen/pkg/kv"};
        s{"(github.com/arr-ai/frozen/internal/iterator)"}{"\1/kvi"};
    }
    print;
}
