// Generated by gen-kv.pl kvi kv.KeyValue. DO NOT EDIT.
package kvi

import (
	"github.com/arr-ai/frozen/errors"
)

// Empty is the empty iterator.
var Empty = empty{}

type empty struct{}

func (empty) Next() bool {
	return false
}

func (empty) Value() elementT {
	panic(errors.WTF)
}
