// Generated by gen-kv.pl. DO NOT EDIT.
package kvt

import (
	"github.com/arr-ai/frozen/errors"
	"github.com/arr-ai/frozen/pkg/kv"
)

type unDefroster struct {
	n node
}

var _ unNode = unDefroster{}

func (d unDefroster) Add(args *CombineArgs, v kv.KeyValue, depth int, h hasher, matches *int) unNode {
	return d.n.Defrost().Add(args, v, depth, h, matches)
}

func (d unDefroster) appendTo([]kv.KeyValue) []kv.KeyValue {
	panic(errors.Unimplemented)
}

func (d unDefroster) Empty() bool {
	return d.n.Empty()
}

func (d unDefroster) Freeze() node {
	return d.n
}

func (d unDefroster) Get(args *EqArgs, v kv.KeyValue, h hasher) *kv.KeyValue {
	return d.n.Get(args, v, h)
}

func (d unDefroster) Remove(args *EqArgs, v kv.KeyValue, depth int, h hasher, matches *int) unNode {
	return d.n.Defrost().Remove(args, v, depth, h, matches)
}
