// Generated by gen-kv.pl. DO NOT EDIT.
package kvt

import (
	"github.com/arr-ai/frozen/pkg/kv"
)

type unNode interface {
	Add(args *CombineArgs, v kv.KeyValue, depth int, h hasher, matches *int) unNode
	Freeze() node
	Get(args *EqArgs, v kv.KeyValue, h hasher) *kv.KeyValue
	Remove(args *EqArgs, v kv.KeyValue, depth int, h hasher, matches *int) unNode

	// For internal use by unNode implementations.

	// copyTo copies all the unNode's elements into dest without triggering a
	// reallocation of the target slice. Returns true iff all elements fit.
	appendTo(dest []kv.KeyValue) []kv.KeyValue
}
