name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.25' ]

    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v4
      with:
        go-version: '${{ matrix.go }}'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build
      run: go build -v ./...

    - name: Test
      run: TESTFLAGS='-cover' make ci

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60.1

  # Much slower, so don't require for PR merge.
  races:
    name: Check for Races
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Test
      run: go test -race -short ./...

  vet:
    name: Structural Vet
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Check out code
      uses: actions/checkout@v4

    - name: Vet
      run: make vet
