name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Install golangci-lint
      run: |
        go get github.com/golangci/golangci-lint/cmd/golangci-lint
        golangci-lint version

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        TESTFLAGS='-race -cover' make
